In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

import kagglehub

In [3]:
kagglehub.login()

path = kagglehub.dataset_download("teejmahal20/airline-passenger-satisfaction")

print("Path to dataset files:", path)

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Path to dataset files: /Users/raymundomc/.cache/kagglehub/datasets/teejmahal20/airline-passenger-satisfaction/versions/1

In [7]:
import os

csv_test = os.path.join(path,"test.csv")
csv_train = os.path.join(path,"train.csv")
df_train = pd.read_csv(csv_train)
df_test = pd.read_csv(csv_test)

print("Files inside:", os.listdir(path))

Files inside: ['test.csv', 'train.csv']

In [8]:
df_train.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [9]:
df_test.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

In [14]:
df_train.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [12]:
df_train.isnull().sum()

Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [18]:
df_train.dropna(inplace=True)
df_train = df_train.drop('Unnamed: 0',axis=1)

In [19]:
df_train.isnull().sum()

id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [20]:
df_train.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [21]:
df_train.columns

Index(['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [23]:
col_names = ['id', 'Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction']

for col in col_names:
    print(df_train[col].value_counts())

id
70172     1
18481     1
26801     1
6259      1
17470     1
         ..
24497     1
87602     1
18956     1
118876    1
62567     1
Name: count, Length: 103594, dtype: int64
Gender
Female    52576
Male      51018
Name: count, dtype: int64
Customer Type
Loyal Customer       84662
disloyal Customer    18932
Name: count, dtype: int64
Age
39    2961
25    2790
40    2569
44    2479
42    2453
      ...
74      47
76      45
79      42
78      33
85      17
Name: count, Length: 75, dtype: int64
Type of Travel
Business travel    71465
Personal Travel    32129
Name: count, dtype: int64
Class
Business    49533
Eco         46593
Eco Plus     7468
Name: count, dtype: int64
Flight Distance
337     659
594     395
404     391
862     368
2475    367
       ...
76        1
1305      1
877       1
732       1
400       1
Name: count, Length: 3802, dtype: int64
Inflight wifi service
3    25789
2    25755
4    19737
1    17781
5    11436
0     3096
Name: count, dtype: int64
Departure/Arrival time convenient
4    25474
5    22333
3    17903
2    17142
1    15452
0     5290
Name: count, dtype: int64
Ease of Online booking
3    24370
2    23962
4    19508
1    17466
5    13815
0     4473
Name: count, dtype: int64
Gate location
3    28489
4    24353
2    19396
1    17511
5    13844
0        1
Name: count, dtype: int64
Food and drink
4    24294
5    22239
3    22238
2    21918
1    12800
0      105
Name: count, dtype: int64
Online boarding
4    30671
3    21744
5    20652
2    17449
1    10658
0     2420
Name: count, dtype: int64
Seat comfort
4    31682
5    26393
3    18641
2    14846
1    12031
0        1
Name: count, dtype: int64
Inflight entertainment
4    29335
5    25145
3    19080
2    17579
1    12441
0       14
Name: count, dtype: int64
On-board service
4    30773
5    23584
3    22770
2    14632
1    11832
0        3
Name: count, dtype: int64
Leg room service
4    28704
5    24599
3    20042
2    19469
1    10310
0      470
Name: count, dtype: int64
Baggage handling
4    37274
5    27047
3    20567
2    11483
1     7223
Name: count, dtype: int64
Checkin service
4    28975
3    28356
5    20556
2    12854
1    12852
0        1
Name: count, dtype: int64
Inflight service
4    37846
5    27041
3    20227
2    11414
1     7063
0        3
Name: count, dtype: int64
Cleanliness
4    27100
3    24506
5    22619
2    16081
1    13276
0       12
Name: count, dtype: int64
Departure Delay in Minutes
0      58552
1       2939
2       2266
3       2006
4       1845
       ...
426        1
465        1
321        1
692        1
337        1
Name: count, Length: 445, dtype: int64
Arrival Delay in Minutes
0.0      58159
1.0       2211
2.0       2064
3.0       1952
4.0       1907
         ...
458.0        1
729.0        1
382.0        1
459.0        1
369.0        1
Name: count, Length: 455, dtype: int64
satisfaction
neutral or dissatisfied    58697
satisfied                  44897
Name: count, dtype: int64

In [ ]:
import category_encoders as ce