In [13]:

from sklearn import tree
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

In [ ]:
import dtreeviz as dt
# from dtreeviz.trees import dtreeviz

In [11]:
import kagglehub

kagglehub.login()

path = kagglehub.dataset_download("divaniazzahra/mental-health-dataset")

print("Path to dataset files: ", path)

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Downloading from https://www.kaggle.com/api/v1/datasets/download/divaniazzahra/mental-health-dataset?dataset_version_number=1...

100%|██████████| 2.34M/2.34M [00:00<00:00, 8.89MB/s]

Extracting files...
Path to dataset files:  /Users/raymundomc/.cache/kagglehub/datasets/divaniazzahra/mental-health-dataset/versions/1

In [32]:
import os
print("Files inside: ", os.listdir(path))

csv_path = os.path.join(path,"Mental Health Dataset.csv")
df = pd.read_csv(csv_path)

Files inside:  ['Mental Health Dataset.csv']

In [33]:
print("Null Check: \n")
print(df.isna().sum())

Null Check:

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

In [34]:
# df.dropna(subset=["self_employed"],inplace=True)

# print("Null Check: \n")
# df.isna().sum()

In [ ]:
known = df[df["self_employed"].notna()]
missing = df[df["self_employed"].isna()]

# these are the features that will help me predict whether one is self employed or in corporate
features = [
    "Gender", "Country", "Occupation", "family_history",
    "treatment", "Days_Indoors", "Growing_Stress",
    "Changes_Habits", "Mental_Health_History",
    "Mood_Swings", "Coping_Struggles", "Work_Interest",
    "Social_Weakness", "mental_health_interview",
    "care_options"
]


# these are the imports I need to help me encode the values instead of NaN values
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# training variables, just assignment what the features to test on the target variable
X_train = known[features]
y_train = known["self_employed"]


# encoding being done
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), features)
    ]
)


model = Pipeline(steps=[
    ("prep", preprocessor),
    ("clf", LogisticRegression(max_iter=1000))
])


model.fit(X_train, y_train)

predicted = model.predict(missing[features])
df.loc[df["self_employed"].isna(), "self_employed"] = predicted

In [40]:
df["Occupation"].values

array(['Corporate', 'Corporate', 'Corporate', ..., 'Business', 'Business',
       'Business'], shape=(292364,), dtype=object)

In [38]:
df.head(10)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,2014-08-27 11:29:31,Female,United States,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,2014-08-27 11:31:50,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,2014-08-27 11:32:39,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,2014-08-27 11:37:59,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,2014-08-27 11:43:36,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
5,2014-08-27 11:49:51,Female,Poland,Corporate,No,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Not sure
6,2014-08-27 11:51:34,Female,Australia,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
7,2014-08-27 11:52:41,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
8,2014-08-27 12:18:38,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
9,2014-08-27 12:37:50,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No

In [22]:
x = df.columns

print("Columns:\n")

for e in x:
    print(e)

Columns:

Timestamp
Gender
Country
Occupation
self_employed
family_history
treatment
Days_Indoors
Growing_Stress
Changes_Habits
Mental_Health_History
Mood_Swings
Coping_Struggles
Work_Interest
Social_Weakness
mental_health_interview
care_options

In [39]:
print("Null Check: \n")
print(df.isna().sum())

Null Check:

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [25]:
df.describe()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
count,292364,292364,292364,292364,287162,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364,292364
unique,734,2,35,5,2,2,2,5,3,3,3,3,2,3,3,3,3
top,2014-08-27 12:31:41,Male,United States,Housewife,No,No,Yes,1-14 days,Maybe,Yes,No,Medium,No,No,Maybe,No,No
freq,780,239850,171308,66351,257994,176832,147606,63548,99985,109523,104018,101064,154328,105843,103393,232166,118886

In [ ]:
features = ["Gender","self_employed","family_history","Days_Indoors","Growing_Stress",""]
target = ["treatment"]